---
pre: <b>Project 1. </b>
title: "Smith College Museum of Art"
weight: 1
summary: "Tips for not creating a monster."
format:
    hugo:
      toc: true
      output-file: "_index.en.md"
      reference-links: true
      code-link: true
---

## Overview

The [Smith College Museum of Art (SCMA)](https://scma.smith.edu/) staff want to better understand how people use the museum website. Project 1 will focus on real SCMA data spanning from July 2021 to June 2022. Your goal is to create a portfolio of data visualizations which help communicate the usage patterns of the SCMA website to museum staff. At the end of Project 1, your visualizations and accompanying reports will be given to the museum staff for them to learn from!

## Project Description

Project 1 will be completed in self-organized teams of 3 to 4. Each member will be creating their own visualizations, but each visualization from the team will be combined into one portfolio. You should not expect the museum staff to be familiar with data, and should explain things in such a way that anyone could understand.

All of the data (aside from the shop) are exported from the museum’s Google analytics platform. You can find the documentation for [Google analytics here](https://support.google.com/analytics); you will need to use it to reference what some of the measures in the data mean. You can choose to supplement the museum data with other data if you would like. The museum data files include the following:

* country_stats: Website visit statistics by country (based on visitor IP address).
* country_users: Website user statistics by country (based on visitor IP address).
* dates: Visit statistics for the website by day.
* landing_page: The website page which people “land” on the website, a.k.a. the first page they view.
* pages: Statistics regarding the specific pages on the museum website.
* referrals: What service visitors are coming from (where they click on the link to the museum website). 
* search: Statistics regarding terms search on the website.
* shop: Data on sales from the museum shop. 
* state_stats: Website visit statistics by state (based on visitor IP address).
* state_users: Website user statistics by state (based on visitor IP address).

[You can find the data files hosted on the course Moodle here](https://moodle.smith.edu/mod/resource/view.php?id=954407). **You should not share these data files anywhere, including your project github repo.**

## Technical Details

You have 2 weeks (until start of class 10/28) to work on the project, including one full day of class time (10/14). You have full freedom to make the project as simple or intricate as you desire. 









This portfolio will include the visualizations, a text narrative of how the visualizations were created, and an analysis of what story the visualizations are meant to convey. The portfolio should be created using Quarto in R studio. I recommend you output to a PDF if you have only static visualizations, or html if your visualizations are interactive; you can choose other formats if they work better for your project.

With your submission, you will include a list of each standard you think you have demonstrated with your project, as well as what proficiency level you think you have demonstrated. Be sure to speak to the specific details in the standard matrix to justify your position.

The team will share one github repo which will serve as your submission. This repo will include all of your code. I recommend creating your visualizations in separate files, and then combining them in your quarto portfolio document. Each individual member will turn in a document on moodle detailing what standards they think they demonstrated in their project and at what level of proficiency. *Be sure to reference the specific requirements in the standard matrix for the proficiency level you have selected.*